ARG BASE_IMAGE=localhost/ffreis/base:local
FROM ${BASE_IMAGE}

USER root

WORKDIR /run

# NOTE: Previously this image attempted to copy a non-existent
# `scripts/entrypoint.sh` into `/run/entrypoint.sh`, which caused
# the Docker build to fail. That COPY and associated chmod have been
# removed to avoid referencing files that are not in the build context.
USER appuser:appgroup
